version: '3'

services:

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    networks:
      - isleinternal
    ports: 
      - 8081:80
    volumes:
      - /sessions
    depends_on:
      - mysql
    restart: 'no'

  mysql:
    image: islandoracollabgroup/isle-mysql
    container_name: isle-a2-mysql
    hostname: mysql
    networks:
      - isleinternal
    volumes:
      - db_data:/var/lib/mysql
      - ./bcol/mysql/config/my.cnf:/etc/alternatives/my.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=ild_mysqlrt_2018
    # restart: unless-stopped

  fedora:
    image: islandoracollabgroup/isle-fedora
    container_name: isle-a2-fedora
    hostname: fedora
    networks:
      - isleinternal
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - mysql
      - solr
    volumes:
    - /zfs-serverpools/barnardcollege/islandora/fedora/data:/usr/local/fedora/data
    - ./bcol/fedora/config/fedora.fcfg:/usr/local/fedora/server/config/fedora.fcfg
    - ./bcol/fedora/config/fedora-users.xml:/usr/local/fedora/server/config/fedora-users.xml
    - ./bcol/fedora/config/filter-drupal.xml:/usr/local/fedora/server/config/filter-drupal.xml 
    - ./bcol/fedoragsearch/config/fgsconfigFinal/fedoragsearch.properties:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/fedoragsearch.properties
    - ./bcol/fedoragsearch/config/fgsconfigFinal/fgsconfigObjects.properties:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/fgsconfigObjects.properties
    - ./bcol/fedoragsearch/config/fgsconfigFinal/index/FgsIndex/index.properties:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/index/FgsIndex/index.properties
    - ./bcol/fedoragsearch/config/fgsconfigFinal/repository/FgsRepos/repository.properties:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/classes/fgsconfigFinal/repository/FgsRepos/repository.properties
    - /dev/null:/usr/local/tomcat/webapps/fedoragsearch/WEB-INF/lib/log4j-over-slf4j-1.5.10.jar  # ha. ridiculous hack.
    # restart: unless-stopped
    command: /usr/local/tomcat/bin/catalina.sh run


  solr:
    image: islandoracollabgroup/isle-solr
    container_name: isle-a2-solr
    hostname: solr
    networks:
      - isleinternal
    ports:
      - "8082:8080"
    tty: true
    depends_on:
      - mysql 
    volumes:
    - /zfs-serverpools/barnardcollege/islandora/solr/collection1/data:/usr/local/solr/collection1/data
    - /zfs-serverpools/barnardcollege/islandora/solr/collection1/conf/schema.xml:/usr/local/solr/collection1/conf/schema.xml
    # restart: unless-stopped

  apache:
    image: islandoracollabgroup/isle-apache
    container_name: isle-a2-apache
    networks:
      isleinternal:
    tty: true
    depends_on:
      - mysql
      - fedora
      - solr
    volumes:
      - ./bcol/apache/conf/sites-enabled:/etc/apache2/sites-enabled
      - ./bcol/apache/conf/certs:/certs:ro #SNAKEOILS
      - /zfs-serverpools/barnardcollege/islandora/html:/var/www/html
    # restart: unless-stopped

  proxy:
    image: nginx
    hostname: belle
    container_name: isle-a2-proxy
    networks:
      docker-external:
        ipv4_address: 192.168.1.210
      isleinternal:
        aliases:
          - belle.benjaminrosner.com
      isleexternal:
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - fedora
      - solr
      - apache
    volumes:
      - ./bcol/proxy/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./bcol/proxy/config/sites:/etc/nginx/conf.d:ro
      - ./bcol/proxy/certs:/certs:ro
    # restart: unless-stopped
    # command: [nginx-debug, '-g', 'daemon off;']

networks:
  isleinternal:
  isleexternal:
  docker-external:
    external: true


volumes:
  db_data:
